# Generated by Django 5.1.15 on 2026-05-20 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorePool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('raw_metadata_json', models.JSONField(blank=True, null=True)),
                ('title_zh', models.TextField(blank=True, default='')),
                ('tags_json', models.JSONField(blank=True, null=True)),
                ('research_question', models.TextField(blank=True, default='')),
                ('methodology', models.TextField(blank=True, default='')),
                ('key_findings_json', models.JSONField(blank=True, null=True)),
                ('llm_reason', models.TextField(blank=True, default='')),
                ('scored_at', models.DateTimeField(blank=True, null=True)),
                ('score_attempts', models.IntegerField(default=0)),
                ('action', models.CharField(blank=True, choices=[('saved', 'Saved'), ('skipped', 'Skipped'), ('passed', 'Passed')], db_index=True, max_length=16, null=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explore_pool', to='subscriptions.subscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explore_pool', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-found_at',),
                'indexes': [models.Index(fields=['tenant', 'subscription', 'action'], name='explore_exp_tenant__261fde_idx'), models.Index(fields=['tenant', 'scored_at'], name='explore_exp_tenant__6a320c_idx')],
                'unique_together': {('subscription', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='TagDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=32)),
                ('source', models.CharField(default='llm', max_length=16)),
                ('alpha', models.FloatField(default=0.5)),
                ('beta', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_dict', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'tag')},
            },
        ),
    ]
