# Generated by Django 5.1.15 on 2026-05-20 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(choices=[('paper_citations', 'Paper Citations'), ('author_works', 'Author Works'), ('topic_search', 'Topic Search')], default='topic_search', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('generated_queries', models.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('target_ref', models.CharField(blank=True, default='', max_length=512)),
                ('query_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('last_filled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_metadata', models.JSONField(default=dict)),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=512)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='subscriptions.subscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_results', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-fetched_at',),
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['tenant', 'active'], name='subscriptio_tenant__d48fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionresult',
            index=models.Index(fields=['tenant', 'subscription'], name='subscriptio_tenant__465160_idx'),
        ),
    ]
