# Generated by Django 5.1.15 on 2026-05-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackwardTrackCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(db_index=True, max_length=256, unique=True)),
                ('result_json', models.JSONField()),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Backward Track Cache',
            },
        ),
        migrations.CreateModel(
            name='ForwardTrackCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(db_index=True, max_length=256, unique=True)),
                ('result_json', models.JSONField()),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Forward Track Cache',
            },
        ),
    ]
