# Generated by Django 5.1.15 on 2026-05-20 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_paper_id', models.IntegerField(db_index=True)),
                ('to_paper_id', models.IntegerField(db_index=True)),
                ('direction', models.CharField(choices=[('forward', 'Forward'), ('backward', 'Backward')], max_length=16)),
                ('ref_index', models.IntegerField(blank=True, null=True)),
                ('ref_title', models.TextField(blank=True, default='')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'from_paper_id'], name='network_edg_tenant__d7e5ad_idx'), models.Index(fields=['tenant', 'to_paper_id'], name='network_edg_tenant__2250a6_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'from_paper_id', 'to_paper_id', 'direction'), name='uq_edge_tenant_from_to_dir')],
            },
        ),
    ]
