"""initial schema

Revision ID: 7f05a0eda4cc
Revises: 
Create Date: 2026-05-13 20:15:09.963491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f05a0eda4cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('issn', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('publisher', sa.String(length=256), nullable=True),
    sa.Column('quality_tier', sa.Integer(), nullable=True),
    sa.Column('is_predatory', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('oa_status', sa.String(length=32), nullable=True),
    sa.Column('source_dataset', sa.String(length=64), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issn')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('target_json', sa.JSON(), nullable=False),
    sa.Column('cron_expr', sa.String(length=64), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_active'), ['active'], unique=False)
        batch_op.create_index('ix_subscriptions_active_next', ['active', 'next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_next_run_at'), ['next_run_at'], unique=False)

    op.create_table('papers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stem', sa.String(length=512), nullable=False),
    sa.Column('doi', sa.String(length=256), nullable=True),
    sa.Column('arxiv_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('authors_json', sa.JSON(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('pdf_path', sa.String(length=1024), nullable=True),
    sa.Column('md_path', sa.String(length=1024), nullable=True),
    sa.Column('insight_path', sa.String(length=1024), nullable=True),
    sa.Column('refs_path', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), server_default=sa.text("'ref'"), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('arxiv_id')
    )
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_papers_doi'), ['doi'], unique=True)
        batch_op.create_index(batch_op.f('ix_papers_stem'), ['stem'], unique=True)

    op.create_table('citations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('citation_key', sa.String(length=256), nullable=True),
    sa.Column('bibtex', sa.Text(), nullable=True),
    sa.Column('apa', sa.Text(), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_citations_paper_id'), ['paper_id'], unique=False)

    op.create_table('edges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_paper_id', sa.Integer(), nullable=False),
    sa.Column('to_paper_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('ref_index', sa.Integer(), nullable=True),
    sa.Column('ref_title', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_paper_id', 'direction', 'ref_index', name='uq_edge_indexed')
    )
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edges_from_paper_id'), ['from_paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_edges_to_paper_id'), ['to_paper_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('jsonl_path', sa.String(length=1024), nullable=False),
    sa.Column('phase', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_paper_id'), ['paper_id'], unique=False)

    op.create_table('subscription_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('raw_metadata_json', sa.JSON(), nullable=True),
    sa.Column('notified', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('found_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_results_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)
        batch_op.create_index('ix_tasks_status_type', ['status', 'type'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_type'))
        batch_op.drop_index('ix_tasks_status_type')
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_paper_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('subscription_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_results_subscription_id'))

    op.drop_table('subscription_results')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_paper_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edges_to_paper_id'))
        batch_op.drop_index(batch_op.f('ix_edges_from_paper_id'))

    op.drop_table('edges')
    with op.batch_alter_table('citations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_citations_paper_id'))

    op.drop_table('citations')
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_papers_stem'))
        batch_op.drop_index(batch_op.f('ix_papers_doi'))

    op.drop_table('papers')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_next_run_at'))
        batch_op.drop_index('ix_subscriptions_active_next')
        batch_op.drop_index(batch_op.f('ix_subscriptions_active'))

    op.drop_table('subscriptions')
    op.drop_table('journals')
    # ### end Alembic commands ###
