"""add_is_core_to_papers

Revision ID: c40c7aeae9fe
Revises: 2497df2cbb3f
Create Date: 2026-05-14 15:01:29.053644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40c7aeae9fe'
down_revision: Union[str, Sequence[str], None] = '2497df2cbb3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_core', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.create_index(batch_op.f('ix_papers_is_core'), ['is_core'], unique=False)

    # 存量数据迁移：root 论文 + 已分析论文均标记为 core
    op.execute("UPDATE papers SET is_core = 1 WHERE source = 'root' OR status = 'analyzed'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_papers_is_core'))
        batch_op.drop_column('is_core')

    # ### end Alembic commands ###
