"""add_backward_track_cache

Revision ID: d1f07bec4a68
Revises: d639cc998c03
Create Date: 2026-05-14 09:52:33.130249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1f07bec4a68'
down_revision: Union[str, Sequence[str], None] = 'd639cc998c03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backward_track_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doi', sa.String(length=256), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backward_track_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backward_track_cache_doi'), ['doi'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backward_track_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backward_track_cache_doi'))

    op.drop_table('backward_track_cache')
    # ### end Alembic commands ###
