"""add paper status and source indexes

Revision ID: e7004de6d36d
Revises: 7f05a0eda4cc
Create Date: 2026-05-13 20:50:14.105015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7004de6d36d'
down_revision: Union[str, Sequence[str], None] = '7f05a0eda4cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.create_index('ix_papers_source', ['source'], unique=False)
        batch_op.create_index('ix_papers_status', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_index('ix_papers_status')
        batch_op.drop_index('ix_papers_source')

    # ### end Alembic commands ###
