# Generated by Django 5.1.15 on 2026-05-20 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.CharField(db_index=True, max_length=512)),
                ('doi', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('arxiv_id', models.CharField(blank=True, max_length=64, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('authors_json', models.JSONField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('journal_id', models.IntegerField(blank=True, null=True)),
                ('pdf_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('md_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('sha1', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('refs_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('root', 'Root'), ('ref', 'Ref'), ('forward', 'Forward'), ('subscription', 'Subscription')], default='ref', max_length=32)),
                ('is_core', models.BooleanField(db_index=True, default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_summary', models.JSONField(blank=True, null=True)),
                ('ai_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='PaperFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=16)),
                ('path', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='papers.paper')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PaperTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_tags', to='papers.paper')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_tags', to='papers.tag')),
            ],
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['tenant', 'status'], name='papers_pape_tenant__01b9bb_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['tenant', 'source'], name='papers_pape_tenant__7c112e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together={('tenant', 'stem')},
        ),
        migrations.AlterUniqueTogether(
            name='paperfile',
            unique_together={('paper', 'file_type')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('tenant', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='papertag',
            unique_together={('paper', 'tag')},
        ),
    ]
