# Generated by Django 5.1.15 on 2026-05-20 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='journal_id',
        ),
        migrations.AddField(
            model_name='paper',
            name='journal',
            field=models.ForeignKey(blank=True, db_column='journal_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='papers', to='journals.journal'),
        ),
    ]
