# Generated by Django 5.1.15 on 2026-05-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=512)),
                ('publisher', models.CharField(blank=True, max_length=256, null=True)),
                ('quality_tier', models.IntegerField(blank=True, null=True)),
                ('is_predatory', models.BooleanField(default=False)),
                ('oa_status', models.CharField(blank=True, max_length=32, null=True)),
                ('source_dataset', models.CharField(blank=True, max_length=64, null=True)),
                ('refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('easyscholar_json', models.JSONField(blank=True, null=True)),
                ('easyscholar_fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
